-- 확장된 팀 데이터 삽입 (25개 팀)
INSERT INTO team (
    team_name,
    backend_count,
    frontend_count,
    ai_count,
    pm_count,
    design_count,
    team_domain,
    member_wanted,
    team_description
) VALUES
      ('프론트엔드 팀', 1, 2, 0, 1, 1, '웹 개발', 'FRONTEND,DESIGN', '사용자 경험을 중시하는 프론트엔드 개발팀입니다.'),
      ('백엔드 팀', 3, 0, 1, 1, 0, '서버 개발', 'BACKEND,AI', '견고한 서버 아키텍처를 구축하는 백엔드팀입니다.'),
      ('풀스택 팀', 2, 2, 1, 1, 1, '전체 개발', 'BACKEND,FRONTEND,AI', '전 영역을 다루는 풀스택 개발팀입니다.'),
      ('AI 스타트업', 1, 1, 3, 1, 1, 'AI/ML', 'AI,BACKEND,FRONTEND', '혁신적인 AI 솔루션을 만드는 스타트업팀입니다.'),
      ('디자인 중심팀', 1, 1, 0, 1, 2, 'UX/UI', 'DESIGN,FRONTEND', '사용자 중심의 디자인을 추구하는 팀입니다.'),
      ('모바일 앱 개발팀', 2, 2, 0, 1, 1, '모바일', 'FRONTEND,BACKEND', '크로스플랫폼 모바일 앱을 개발하는 팀입니다.'),
      ('데이터 분석팀', 1, 0, 3, 1, 0, '데이터 분석', 'AI,BACKEND', '빅데이터 분석과 인사이트 도출을 하는 팀입니다.'),
      ('게임 개발팀', 2, 1, 1, 1, 2, '게임', 'BACKEND,DESIGN', '재미있는 게임을 만드는 개발팀입니다.'),
      ('핀테크 스타트업', 2, 1, 1, 1, 1, '핀테크', 'BACKEND,FRONTEND', '금융 서비스 혁신을 추구하는 팀입니다.'),
      ('헬스케어 팀', 1, 1, 2, 1, 1, '헬스케어', 'AI,BACKEND', '의료 기술 혁신을 위한 개발팀입니다.'),
      ('이커머스 팀', 2, 2, 0, 1, 1, '이커머스', 'BACKEND,FRONTEND', '온라인 쇼핑몰 플랫폼을 개발하는 팀입니다.'),
      ('교육 플랫폼팀', 1, 2, 1, 1, 1, '교육', 'FRONTEND,AI', '에듀테크 솔루션을 개발하는 팀입니다.'),
      ('IoT 개발팀', 2, 1, 1, 1, 0, 'IoT', 'BACKEND,AI', 'IoT 디바이스와 서비스를 개발하는 팀입니다.'),
      ('블록체인 팀', 3, 1, 0, 1, 0, '블록체인', 'BACKEND', '블록체인 기술을 활용한 서비스를 개발합니다.'),
      ('소셜 미디어팀', 1, 2, 1, 1, 2, '소셜미디어', 'FRONTEND,DESIGN', 'SNS 플랫폼을 개발하는 팀입니다.'),
      ('클라우드 서비스팀', 3, 0, 1, 1, 0, '클라우드', 'BACKEND,AI', '클라우드 인프라 서비스를 개발합니다.'),
      ('머신러닝 연구팀', 0, 1, 4, 1, 0, 'ML 연구', 'AI,BACKEND', '최첨단 ML 알고리즘을 연구하는 팀입니다.'),
      ('웹3 개발팀', 2, 2, 0, 1, 1, 'Web3', 'BACKEND,FRONTEND', '탈중앙화 웹 서비스를 개발합니다.'),
      ('로봇 소프트웨어팀', 2, 0, 2, 1, 0, '로봇공학', 'AI,BACKEND', '로봇 제어 소프트웨어를 개발합니다.'),
      ('사이버보안 팀', 3, 1, 0, 1, 0, '보안', 'BACKEND', '사이버보안 솔루션을 개발하는 팀입니다.'),
      ('AR/VR 팀', 1, 1, 1, 1, 2, 'AR/VR', 'FRONTEND,DESIGN', '가상현실 경험을 만드는 팀입니다.'),
      ('자율주행 팀', 1, 0, 3, 1, 0, '자율주행', 'AI,BACKEND', '자율주행 기술을 개발하는 팀입니다.'),
      ('농업 ICT팀', 1, 1, 2, 1, 1, '농업기술', 'AI,BACKEND', '스마트팜 솔루션을 개발합니다.'),
      ('환경 모니터링팀', 1, 1, 2, 1, 1, '환경', 'AI,FRONTEND', '환경 데이터 분석 플랫폼을 개발합니다.'),
      ('스포츠 테크팀', 1, 1, 1, 1, 1, '스포츠', 'AI,FRONTEND', '스포츠 분석 서비스를 개발하는 팀입니다.');

-- 확장된 사용자 데이터 삽입 (100명)
INSERT INTO USERS (
    role,
    user_name,
    user_email,
    major,
    last_class,
    user_profile,
    project_experience,
    qualification,
    team_id
) VALUES
-- 기존 팀 멤버들 (30명 - 30%)
('student', '김프론트1', 'frontend1@test.com', true, 4, '프론트엔드 개발에 열정적인 학생입니다.', 'React 프로젝트 3개 경험', '정보처리기사', 1),
('student', '이디자인1', 'design1@test.com', false, 3, 'UI/UX 디자인을 전공하고 있습니다.', '앱 디자인 2개 프로젝트', 'GTQ 1급', 1),
('student', '박백엔드1', 'backend1@test.com', true, 4, '서버 개발과 데이터베이스에 관심이 많습니다.', 'Spring Boot 프로젝트 5개', '정보처리기사', 2),
('student', '최AI1', 'ai1@test.com', true, 4, '머신러닝과 딥러닝을 공부하고 있습니다.', 'Python ML 프로젝트 3개', 'ADsP', 2),
('student', '정풀스택1', 'fullstack1@test.com', true, 4, '프론트엔드와 백엔드 모두 경험이 있습니다.', '풀스택 프로젝트 4개', 'AWS 자격증', 3),
('student', '김모바일1', 'mobile1@test.com', true, 4, 'Flutter로 모바일 앱을 개발합니다.', 'Flutter 앱 5개 개발', '정보처리기사', 6),
('student', '이데이터1', 'data1@test.com', true, 4, '데이터 사이언스를 전공하고 있습니다.', 'Python 데이터 분석 프로젝트 4개', 'ADsP', 7),
('student', '박게임1', 'game1@test.com', false, 3, 'Unity로 게임을 개발하는 학생입니다.', 'Unity 게임 3개 제작', 'Unity 인증', 8),
('student', '최핀테크1', 'fintech1@test.com', true, 4, '금융 서비스 개발에 관심이 있습니다.', 'Spring Boot 금융 앱 개발', 'SQLD', 9),
('student', '정헬스1', 'health1@test.com', true, 4, '의료 IT 분야를 공부하고 있습니다.', '병원 관리 시스템 개발', 'ITQ', 10),
('student', '김커머스1', 'commerce1@test.com', false, 3, '이커머스 플랫폼 개발자입니다.', 'Node.js 쇼핑몰 개발', 'AWS 자격증', 11),
('student', '이에듀1', 'edu1@test.com', true, 4, '교육 분야의 개발자가 되고 싶습니다.', '학습 관리 시스템 개발', '정보처리기사', 12),
('student', 'IoT개발자1', 'iot1@test.com', true, 4, 'IoT 디바이스 제어에 관심이 많습니다.', 'Arduino 프로젝트 6개', 'IoT 지식능력검정', 13),
('student', '블록체인1', 'blockchain1@test.com', true, 4, '블록체인 기술을 연구하고 있습니다.', 'Solidity 스마트컨트랙트 개발', 'CBCP', 14),
('student', '소셜1', 'social1@test.com', false, 3, 'SNS 서비스 개발에 흥미가 있습니다.', 'React SNS 앱 개발', 'OPIc IM', 15),
('student', '클라우드1', 'cloud1@test.com', true, 4, '클라우드 아키텍처를 공부합니다.', 'AWS 인프라 구축 경험', 'AWS SAA', 16),
('student', 'ML연구자1', 'ml1@test.com', true, 4, '머신러닝 논문 구현에 집중합니다.', 'PyTorch 논문 구현 5개', 'ADSP', 17),
('student', 'Web3개발자1', 'web3_1@test.com', true, 4, '탈중앙화 앱을 개발하고 있습니다.', 'DApp 개발 경험 3개', 'CBCP', 18),
('student', '로봇SW1', 'robot1@test.com', true, 4, '로봇 제어 알고리즘을 연구합니다.', 'ROS 기반 로봇 제어', '임베디드SW자격증', 19),
('student', '보안전문가1', 'security1@test.com', true, 4, '사이버보안 전문가가 목표입니다.', '해킹 방어 시스템 개발', '정보보안기사', 20),
('student', 'VR개발자1', 'vr1@test.com', false, 3, 'VR 콘텐츠를 제작하고 있습니다.', 'Unity VR 앱 4개', 'Unity 인증', 21),
('student', '자율주행1', 'autonomous1@test.com', true, 4, '자율주행 기술을 연구하고 있습니다.', 'OpenCV 자율주행 시뮬레이션', 'ADSP', 22),
('student', '농업ICT1', 'agri1@test.com', true, 4, '스마트팜 기술에 관심이 있습니다.', 'IoT 기반 농업 모니터링', 'IoT 지식능력검정', 23),
('student', '환경모니터1', 'env1@test.com', false, 3, '환경 데이터 분석을 전공합니다.', '대기질 예측 모델 개발', 'ADSP', 24),
('student', '스포츠테크1', 'sports1@test.com', true, 4, '스포츠 분석 서비스를 개발합니다.', '축구 경기 분석 앱', 'SQLD', 25),
('student', '김프론트2', 'frontend2@test.com', true, 3, '프론트엔드 신입 개발자입니다.', 'Vue.js 개인 프로젝트 2개', 'ITQ', 4),
('student', '이백엔드2', 'backend2@test.com', true, 4, '백엔드 시스템 설계에 능숙합니다.', 'Django 웹 서비스 개발', '정보처리기사', 5),
('student', '박AI2', 'ai2@test.com', true, 4, 'NLP와 컴퓨터비전을 연구합니다.', 'Transformer 모델 구현', 'ADSP', 4),
('student', '최디자인2', 'design2@test.com', false, 3, '사용자 중심 디자인을 추구합니다.', '모바일 앱 UI/UX 디자인 10개', 'GTQ 1급', 5),
('student', '정PM2', 'pm2@test.com', false, 4, '프로젝트 관리 전문가입니다.', '애자일 프로젝트 관리 경험 5회', 'PMP', 3),

-- 팀이 없는 후보자들 (70명)
('student', '홍길동', 'hong@test.com', true, 4, '새로운 팀을 찾고 있는 백엔드 개발자입니다.', 'Java Spring 프로젝트 경험', '정보처리기사', NULL),
('student', '김철수', 'kim@test.com', false, 3, '프론트엔드 개발을 배우고 있는 학생입니다.', 'React 독학 중', NULL, NULL),
('student', '이영희', 'lee@test.com', true, 4, '데이터 분석과 AI에 관심이 있습니다.', 'Python 데이터 분석 프로젝트', 'ADsP', NULL),
('student', '박민수', 'park@test.com', false, 2, '디자인과 프론트엔드에 관심이 있습니다.', '포트폴리오 사이트 제작', NULL, NULL),
('student', '조현우', 'cho@test.com', true, 4, '팀 리딩 경험이 있는 PM 지망생입니다.', '프로젝트 관리 경험 2회', 'PMP 준비중', NULL),
('student', '강백엔드', 'kang_backend@test.com', true, 4, 'Node.js 백엔드 개발자입니다.', 'Express.js API 개발 4개', 'AWS SAA', NULL),
('student', '윤프론트', 'yoon_front@test.com', false, 3, 'Angular 프레임워크를 공부합니다.', 'Angular 프로젝트 3개', 'ITQ', NULL),
('student', '임AI연구', 'lim_ai@test.com', true, 4, 'Computer Vision 연구자입니다.', 'OpenCV 프로젝트 6개', 'ADSP', NULL),
('student', '한디자이너', 'han_design@test.com', false, 3, 'UI/UX 디자인 전문가입니다.', 'Figma 디자인 시스템 구축', 'GTQ 1급', NULL),
('student', '오PM', 'oh_pm@test.com', true, 4, '스크럼 마스터 경험이 있습니다.', '애자일 방법론 적용 10회', 'CSM', NULL),
('student', '서풀스택', 'seo_full@test.com', true, 4, 'MERN 스택 개발자입니다.', '풀스택 웹앱 개발 5개', 'MongoDB 자격증', NULL),
('student', '노모바일', 'no_mobile@test.com', false, 3, 'React Native 개발자입니다.', '크로스플랫폼 앱 개발 3개', 'Google Play Console 경험', NULL),
('student', '문데이터', 'moon_data@test.com', true, 4, '빅데이터 분석 전문가입니다.', 'Spark 데이터 파이프라인 구축', 'ADSP', NULL),
('student', '유게임', 'yu_game@test.com', true, 3, 'Unreal Engine 개발자입니다.', 'UE4 게임 개발 2개', 'Unreal 인증', NULL),
('student', '진보안', 'jin_security@test.com', true, 4, '화이트해커를 꿈꿉니다.', '해킹 대회 입상 3회', '정보보안기사', NULL),
('student', '배블록체인', 'bae_blockchain@test.com', true, 4, 'DeFi 서비스를 개발합니다.', 'Solidity 컨트랙트 개발 5개', 'CBCP', NULL),
('student', '황클라우드', 'hwang_cloud@test.com', true, 4, 'DevOps 엔지니어 지망생입니다.', 'Kubernetes 클러스터 관리', 'CKA', NULL),
('student', '신IoT', 'shin_iot@test.com', false, 3, '스마트홈 서비스를 개발합니다.', '라즈베리파이 프로젝트 8개', 'IoT 지식능력검정', NULL),
('student', '곽머신러닝', 'kwak_ml@test.com', true, 4, 'AutoML 연구를 하고 있습니다.', 'Kaggle 컴페티션 참가 5회', 'Kaggle Expert', NULL),
('student', '성웹개발', 'sung_web@test.com', false, 3, '웹 표준을 준수한 개발을 합니다.', 'Semantic HTML 웹사이트 제작', 'W3C 인증', NULL),
('student', '민앱개발', 'min_app@test.com', true, 4, 'Flutter로 크로스플랫폼 앱을 만듭니다.', 'Flutter 앱 스토어 출시 2개', 'Flutter 인증', NULL),
('student', '차AR개발', 'cha_ar@test.com', false, 3, 'AR 콘텐츠 제작자입니다.', 'ARCore 앱 개발 3개', 'Google AR 인증', NULL),
('student', '표VR개발', 'pyo_vr@test.com', true, 4, 'VR 교육 콘텐츠를 제작합니다.', 'Oculus VR 앱 개발', 'Oculus 개발자', NULL),
('student', '남로봇', 'nam_robot@test.com', true, 4, '자율 로봇 개발자입니다.', 'ROS2 기반 로봇 개발', 'ROS 자격증', NULL),
('student', '공자율주행', 'kong_auto@test.com', true, 4, '자율주행 알고리즘을 연구합니다.', 'CARLA 시뮬레이션 경험', 'NVIDIA 자격증', NULL),
('student', '마핀테크', 'ma_fintech@test.com', false, 3, '디지털 뱅킹 서비스를 개발합니다.', '금융 API 연동 경험 5회', 'SQLD', NULL),
('student', '도헬스케어', 'do_health@test.com', true, 4, '의료 AI 서비스를 개발합니다.', '의료 영상 분석 AI 개발', 'ADSP', NULL),
('student', '송이커머스', 'song_ecom@test.com', false, 3, '온라인 쇼핑몰을 개발합니다.', 'Shopify 커스터마이징', 'Shopify 파트너', NULL),
('student', '원에듀테크', 'won_edu@test.com', true, 4, '교육 플랫폼을 개발합니다.', 'LMS 시스템 개발 경험', '정보처리기사', NULL),
('student', '천소셜', 'cheon_social@test.com', false, 3, 'SNS 서비스 기획자입니다.', 'Instagram 클론 개발', 'OPIC IM', NULL),
('student', '방환경', 'bang_env@test.com', true, 4, '환경 모니터링 시스템을 개발합니다.', '대기질 센서 데이터 분석', '환경기사', NULL),
('student', '변스포츠', 'byun_sports@test.com', true, 4, '스포츠 데이터 분석가입니다.', '야구 세이버메트릭스 분석', 'ADSP', NULL),
('student', '오농업', 'oh_agri@test.com', false, 3, '스마트팜 솔루션을 개발합니다.', '농업 센서 네트워크 구축', '정보처리기능사', NULL),
('student', '하엣지', 'ha_edge@test.com', true, 4, '엣지 컴퓨팅을 연구합니다.', '엣지 AI 모델 최적화', 'NVIDIA 자격증', NULL),
('student', '허사이버', 'heo_cyber@test.com', true, 4, '사이버보안 연구자입니다.', '취약점 분석 도구 개발', '정보보안기사', NULL),
('student', '고퀀트', 'go_quant@test.com', true, 4, '알고리즘 트레이딩을 연구합니다.', '파이썬 퀀트 전략 개발', 'FRM', NULL),
('student', '권드론', 'kwon_drone@test.com', false, 3, '드론 소프트웨어를 개발합니다.', '드론 자율비행 시스템 개발', '무인항공기 자격증', NULL),
('student', '금음성', 'geum_voice@test.com', true, 4, '음성 인식 기술을 연구합니다.', 'STT/TTS 모델 개발', 'ADSP', NULL),
('student', '김번역', 'kim_trans@test.com', false, 3, '기계번역 시스템을 개발합니다.', 'Transformer 번역 모델', 'TOEIC 950', NULL),
('student', '나추천', 'na_recom@test.com', true, 4, '추천 시스템을 연구합니다.', '협업 필터링 구현', 'Netflix Prize 참가', NULL),
('student', '다검색', 'da_search@test.com', true, 4, '검색 엔진을 개발합니다.', 'Elasticsearch 클러스터 구축', 'Elastic 인증', NULL),
('student', '라챗봇', 'ra_chatbot@test.com', false, 3, 'AI 챗봇을 개발합니다.', 'DialogFlow 챗봇 개발 5개', 'Google Cloud 인증', NULL),
('student', '만컴비전', 'man_cv@test.com', true, 4, '컴퓨터 비전 엔지니어입니다.', '객체 탐지 모델 개발', 'YOLO 모델 튜닝 경험', NULL),
('student', '반자연어', 'ban_nlp@test.com', true, 4, 'NLP 연구자입니다.', 'BERT 기반 텍스트 분류', 'Hugging Face 기여자', NULL),
('student', '밤강화학습', 'bam_rl@test.com', true, 4, '강화학습을 연구합니다.', 'OpenAI Gym 환경 개발', 'DeepMind 논문 구현', NULL),
('student', '법연합학습', 'beop_fl@test.com', false, 3, '연합학습을 연구합니다.', '프라이버시 보존 ML 연구', 'Privacy 학회 발표', NULL),
('student', '병양자', 'byung_quantum@test.com', true, 4, '양자 컴퓨팅을 공부합니다.', 'Qiskit 양자 알고리즘', 'IBM Quantum 인증', NULL),
('student', '보신경망', 'bo_neural@test.com', true, 4, '신경망 아키텍처를 연구합니다.', 'ResNet 변형 모델 개발', 'PyTorch Lightning 경험', NULL),
('student', '복최적화', 'bok_opt@test.com', false, 3, '최적화 알고리즘을 연구합니다.', '유전 알고리즘 구현', '수리최적화 학회 참가', NULL),
('student', '분시계열', 'bun_ts@test.com', true, 4, '시계열 분석 전문가입니다.', 'LSTM 시계열 예측 모델', '시계열 분석 자격증', NULL),
('student', '불그래프', 'bul_graph@test.com', true, 4, '그래프 신경망을 연구합니다.', 'GNN 논문 구현 3개', 'PyTorch Geometric 기여자', NULL),
('student', '브연결성', 'br_connect@test.com', false, 3, '네트워크 분석을 전공합니다.', '소셜 네트워크 분석', 'NetworkX 전문가', NULL),
('student', '비추론', 'bi_inference@test.com', true, 4, '베이지안 추론을 연구합니다.', 'PyMC3 베이지안 모델링', '베이지안 통계 자격증', NULL),
('student', '빅생성', 'big_gen@test.com', true, 4, '생성 모델을 연구합니다.', 'GAN/VAE 모델 개발', 'NIPS 논문 리뷰어', NULL),
('student', '사전이학습', 'sa_pretrain@test.com', false, 3, '전이학습을 연구합니다.', 'Fine-tuning 전문가', 'Transformers 라이브러리 기여', NULL),
('student', '산멀티모달', 'san_multi@test.com', true, 4, '멀티모달 AI를 연구합니다.', 'CLIP 모델 응용 개발', 'Vision-Language 연구', NULL),
('student', '삼분산', 'sam_dist@test.com', true, 4, '분산 시스템을 개발합니다.', 'Apache Kafka 클러스터 운영', 'Confluent 인증', NULL),
('student', '상컨테이너', 'sang_container@test.com', false, 3, '컨테이너 기술을 전문으로 합니다.', 'Docker Swarm 클러스터 관리', 'Docker 인증', NULL),
('student', '색마이크로', 'saek_micro@test.com', true, 4, '마이크로서비스를 설계합니다.', 'Spring Cloud 마이크로서비스', 'AWS 마이크로서비스 인증', NULL),
('student', '생서버리스', 'saeng_serverless@test.com', true, 4, '서버리스 아키텍처를 연구합니다.', 'AWS Lambda 함수 개발 20개', 'AWS SAA', NULL),
('student', '서API', 'seo_api@test.com', false, 3, 'RESTful API 설계 전문가입니다.', 'OpenAPI 스펙 작성 경험', 'Postman 인증', NULL),
('student', '속그래픽스', 'sok_graphics@test.com', true, 4, '컴퓨터 그래픽스를 연구합니다.', 'OpenGL 3D 엔진 개발', 'OpenGL 인증', NULL),
('student', '손웹GL', 'son_webgl@test.com', false, 3, 'WebGL로 3D 웹을 개발합니다.', 'Three.js 인터랙티브 사이트', 'Three.js 전문가', NULL),
('student', '솔메타버스', 'sol_metaverse@test.com', true, 4, '메타버스 플랫폼을 개발합니다.', 'VRChat 월드 개발 5개', 'Unity VR 인증', NULL),
('student', '송NFT', 'song_nft@test.com', true, 4, 'NFT 마켓플레이스를 개발합니다.', 'ERC-721 컨트랙트 개발', 'Ethereum 개발자', NULL),
('student', '수DAO', 'su_dao@test.com', false, 3, 'DAO 거버넌스를 연구합니다.', '탈중앙화 투표 시스템 개발', 'Web3 Foundation 그랜트', NULL),
('student', '순크로스체인', 'sun_cross@test.com', true, 4, '크로스체인 기술을 개발합니다.', '브릿지 프로토콜 개발', 'Polkadot 개발자', NULL),
('student', '술DeFi', 'sul_defi@test.com', true, 4, 'DeFi 프로토콜을 개발합니다.', 'AMM 프로토콜 구현', 'Uniswap V3 연구', NULL),
('student', '숨오라클', 'sum_oracle@test.com', false, 3, '블록체인 오라클을 개발합니다.', 'Chainlink 노드 운영', 'Chainlink 개발자', NULL),
('student', '쉬Layer2', 'swi_layer2@test.com', true, 4, 'Layer 2 솔루션을 연구합니다.', 'Optimistic Rollup 개발', 'Ethereum L2 전문가', NULL),
('student', '스ZKP', 'seu_zkp@test.com', true, 4, '영지식 증명을 연구합니다.', 'zk-SNARK 회로 개발', 'Zero Knowledge 연구자', NULL);

-- 사용자 포지션 정보 (wanted_position) - 100명 분
INSERT INTO USER_WANTED_POSITION (user_user_id, wanted_position) VALUES
-- 기존 팀 멤버들 (1-30)
(1, 'FRONTEND'), (1, 'DESIGN'),
(2, 'DESIGN'), (2, 'FRONTEND'),
(3, 'BACKEND'), (3, 'AI'),
(4, 'AI'), (4, 'BACKEND'),
(5, 'FRONTEND'), (5, 'BACKEND'),
(6, 'FRONTEND'), (6, 'BACKEND'),
(7, 'AI'), (7, 'BACKEND'),
(8, 'BACKEND'), (8, 'DESIGN'),
(9, 'BACKEND'), (9, 'FRONTEND'),
(10, 'AI'), (10, 'BACKEND'),
(11, 'BACKEND'), (11, 'FRONTEND'),
(12, 'FRONTEND'), (12, 'AI'),
(13, 'BACKEND'), (13, 'AI'),
(14, 'BACKEND'),
(15, 'FRONTEND'), (15, 'DESIGN'),
(16, 'BACKEND'), (16, 'AI'),
(17, 'AI'), (17, 'BACKEND'),
(18, 'BACKEND'), (18, 'FRONTEND'),
(19, 'AI'), (19, 'BACKEND'),
(20, 'BACKEND'),
(21, 'FRONTEND'), (21, 'DESIGN'),
(22, 'AI'), (22, 'BACKEND'),
(23, 'AI'), (23, 'BACKEND'),
(24, 'AI'), (24, 'FRONTEND'),
(25, 'AI'), (25, 'FRONTEND'),
(26, 'FRONTEND'), (26, 'AI'),
(27, 'BACKEND'), (27, 'AI'),
(28, 'AI'), (28, 'BACKEND'),
(29, 'DESIGN'), (29, 'FRONTEND'),
(30, 'PM'), (30, 'BACKEND'),

-- 팀이 없는 후보자들 (31-100)
(31, 'BACKEND'), (31, 'AI'),
(32, 'FRONTEND'), (32, 'DESIGN'),
(33, 'AI'), (33, 'BACKEND'),
(34, 'DESIGN'), (34, 'FRONTEND'),
(35, 'PM'), (35, 'BACKEND'),
(36, 'BACKEND'),
(37, 'FRONTEND'),
(38, 'AI'),
(39, 'DESIGN'),
(40, 'PM'),
(41, 'BACKEND'), (41, 'FRONTEND'),
(42, 'FRONTEND'),
(43, 'AI'), (43, 'BACKEND'),
(44, 'BACKEND'),
(45, 'BACKEND'),
(46, 'BACKEND'),
(47, 'BACKEND'),
(48, 'BACKEND'), (48, 'AI'),
(49, 'AI'),
(50, 'FRONTEND'),
(51, 'FRONTEND'),
(52, 'FRONTEND'), (52, 'DESIGN'),
(53, 'FRONTEND'), (53, 'DESIGN'),
(54, 'BACKEND'), (54, 'AI'),
(55, 'AI'), (55, 'BACKEND'),
(56, 'BACKEND'),
(57, 'AI'), (57, 'BACKEND'),
(58, 'FRONTEND'), (58, 'BACKEND'),
(59, 'FRONTEND'),
(60, 'FRONTEND'), (60, 'DESIGN'),
(61, 'AI'), (61, 'BACKEND'),
(62, 'AI'), (62, 'BACKEND'),
(63, 'BACKEND'), (63, 'AI'),
(64, 'BACKEND'),
(65, 'BACKEND'),
(66, 'BACKEND'),
(67, 'AI'),
(68, 'AI'),
(69, 'FRONTEND'),
(70, 'AI'),
(71, 'FRONTEND'), (71, 'DESIGN'),
(72, 'AI'),
(73, 'AI'),
(74, 'AI'),
(75, 'AI'),
(76, 'AI'),
(77, 'AI'),
(78, 'AI'),
(79, 'AI'),
(80, 'AI'),
(81, 'AI'),
(82, 'AI'),
(83, 'AI'),
(84, 'AI'),
(85, 'AI'),
(86, 'AI'),
(87, 'AI'),
(88, 'AI'),
(89, 'AI'),
(90, 'AI'),
(91, 'BACKEND'),
(92, 'BACKEND'),
(93, 'BACKEND'),
(94, 'BACKEND'),
(95, 'FRONTEND'),
(96, 'FRONTEND'),
(97, 'BACKEND'),
(98, 'BACKEND'),
(99, 'BACKEND'),
(100, 'AI');

-- 사용자 프로젝트 목표 (project_preference) - 100명 분
INSERT INTO USER_PROJECT_GOAL (user_user_id, project_preference) VALUES
-- 기존 팀 멤버들 (1-30)
(1, 'PORTFOLIO'), (1, 'STUDY'),
(2, 'PORTFOLIO'), (2, 'IDEA'),
(3, 'PROFESSIONAL'), (3, 'QUALITY'),
(4, 'STUDY'), (4, 'IDEA'),
(5, 'JOB'), (5, 'PROFESSIONAL'),
(6, 'PORTFOLIO'), (6, 'JOB'),
(7, 'PROFESSIONAL'), (7, 'AWARD'),
(8, 'IDEA'), (8, 'PORTFOLIO'),
(9, 'JOB'), (9, 'PROFESSIONAL'),
(10, 'STUDY'), (10, 'IDEA'),
(11, 'PORTFOLIO'), (11, 'JOB'),
(12, 'STUDY'), (12, 'PORTFOLIO'),
(13, 'PROFESSIONAL'), (13, 'QUALITY'),
(14, 'IDEA'), (14, 'AWARD'),
(15, 'PORTFOLIO'), (15, 'STUDY'),
(16, 'PROFESSIONAL'), (16, 'QUALITY'),
(17, 'AWARD'), (17, 'PROFESSIONAL'),
(18, 'IDEA'), (18, 'PROFESSIONAL'),
(19, 'PROFESSIONAL'), (19, 'AWARD'),
(20, 'PROFESSIONAL'), (20, 'QUALITY'),
(21, 'PORTFOLIO'), (21, 'IDEA'),
(22, 'PROFESSIONAL'), (22, 'AWARD'),
(23, 'STUDY'), (23, 'IDEA'),
(24, 'PORTFOLIO'), (24, 'STUDY'),
(25, 'PORTFOLIO'), (25, 'STUDY'),
(26, 'PORTFOLIO'), (26, 'STUDY'),
(27, 'PROFESSIONAL'), (27, 'QUALITY'),
(28, 'STUDY'), (28, 'IDEA'),
(29, 'PORTFOLIO'), (29, 'IDEA'),
(30, 'JOB'), (30, 'PROFESSIONAL'),

-- 팀이 없는 후보자들 (31-100)
(31, 'JOB'), (31, 'PROFESSIONAL'),
(32, 'STUDY'), (32, 'PORTFOLIO'),
(33, 'IDEA'), (33, 'STUDY'),
(34, 'PORTFOLIO'), (34, 'IDEA'),
(35, 'JOB'), (35, 'PROFESSIONAL'),
(36, 'PROFESSIONAL'), (36, 'QUALITY'),
(37, 'STUDY'), (37, 'PORTFOLIO'),
(38, 'AWARD'), (38, 'PROFESSIONAL'),
(39, 'PORTFOLIO'), (39, 'IDEA'),
(40, 'JOB'), (40, 'PROFESSIONAL'),
(41, 'PORTFOLIO'), (41, 'JOB'),
(42, 'STUDY'), (42, 'PORTFOLIO'),
(43, 'PROFESSIONAL'), (43, 'AWARD'),
(44, 'IDEA'), (44, 'PORTFOLIO'),
(45, 'PROFESSIONAL'), (45, 'QUALITY'),
(46, 'IDEA'), (46, 'AWARD'),
(47, 'JOB'), (47, 'PROFESSIONAL'),
(48, 'STUDY'), (48, 'IDEA'),
(49, 'AWARD'), (49, 'PROFESSIONAL'),
(50, 'PORTFOLIO'), (50, 'STUDY'),
(51, 'STUDY'), (51, 'PORTFOLIO'),
(52, 'PORTFOLIO'), (52, 'IDEA'),
(53, 'PORTFOLIO'), (53, 'STUDY'),
(54, 'PROFESSIONAL'), (54, 'AWARD'),
(55, 'IDEA'), (55, 'STUDY'),
(56, 'JOB'), (56, 'PROFESSIONAL'),
(57, 'PROFESSIONAL'), (57, 'AWARD'),
(58, 'PORTFOLIO'), (58, 'JOB'),
(59, 'STUDY'), (59, 'PORTFOLIO'),
(60, 'PORTFOLIO'), (60, 'IDEA'),
(61, 'PROFESSIONAL'), (61, 'AWARD'),
(62, 'STUDY'), (62, 'IDEA'),
(63, 'JOB'), (63, 'PROFESSIONAL'),
(64, 'PROFESSIONAL'), (64, 'QUALITY'),
(65, 'IDEA'), (65, 'AWARD'),
(66, 'PORTFOLIO'), (66, 'JOB'),
(67, 'AWARD'), (67, 'PROFESSIONAL'),
(68, 'STUDY'), (68, 'IDEA'),
(69, 'PORTFOLIO'), (69, 'STUDY'),
(70, 'PROFESSIONAL'), (70, 'AWARD'),
(71, 'PORTFOLIO'), (71, 'IDEA'),
(72, 'AWARD'), (72, 'PROFESSIONAL'),
(73, 'STUDY'), (73, 'IDEA'),
(74, 'PROFESSIONAL'), (74, 'AWARD'),
(75, 'AWARD'), (75, 'PROFESSIONAL'),
(76, 'STUDY'), (76, 'IDEA'),
(77, 'PROFESSIONAL'), (77, 'AWARD'),
(78, 'IDEA'), (78, 'STUDY'),
(79, 'AWARD'), (79, 'PROFESSIONAL'),
(80, 'PROFESSIONAL'), (80, 'QUALITY'),
(81, 'STUDY'), (81, 'IDEA'),
(82, 'PROFESSIONAL'), (82, 'AWARD'),
(83, 'AWARD'), (83, 'PROFESSIONAL'),
(84, 'STUDY'), (84, 'IDEA'),
(85, 'PROFESSIONAL'), (85, 'AWARD'),
(86, 'IDEA'), (86, 'STUDY'),
(87, 'AWARD'), (87, 'PROFESSIONAL'),
(88, 'PROFESSIONAL'), (88, 'QUALITY'),
(89, 'STUDY'), (89, 'IDEA'),
(90, 'PROFESSIONAL'), (90, 'AWARD'),
(91, 'PROFESSIONAL'), (91, 'QUALITY'),
(92, 'JOB'), (92, 'PROFESSIONAL'),
(93, 'PROFESSIONAL'), (93, 'AWARD'),
(94, 'JOB'), (94, 'PROFESSIONAL'),
(95, 'PORTFOLIO'), (95, 'STUDY'),
(96, 'PORTFOLIO'), (96, 'IDEA'),
(97, 'IDEA'), (97, 'AWARD'),
(98, 'PROFESSIONAL'), (98, 'QUALITY'),
(99, 'IDEA'), (99, 'AWARD'),
(100, 'AWARD'), (100, 'PROFESSIONAL');

-- 사용자 프로젝트 분위기 (personal_preference) - 100명 분
INSERT INTO USER_PROJECT_VIVE (user_user_id, personal_preference) VALUES
-- 기존 팀 멤버들 (1-30)
(1, 'COMFY'), (1, 'DEMOCRACY'),
(2, 'COMFY'), (2, 'BRANDNEW'),
(3, 'RULE'), (3, 'LEADER'),
(4, 'COMFY'), (4, 'BRANDNEW'),
(5, 'DEMOCRACY'), (5, 'AGILE'),
(6, 'COMFY'), (6, 'DEMOCRACY'),
(7, 'RULE'), (7, 'LEADER'),
(8, 'BRANDNEW'), (8, 'AGILE'),
(9, 'FORMAL'), (9, 'LEADER'),
(10, 'COMFY'), (10, 'BRANDNEW'),
(11, 'DEMOCRACY'), (11, 'AGILE'),
(12, 'COMFY'), (12, 'DEMOCRACY'),
(13, 'RULE'), (13, 'LEADER'),
(14, 'BRANDNEW'), (14, 'AGILE'),
(15, 'COMFY'), (15, 'DEMOCRACY'),
(16, 'RULE'), (16, 'LEADER'),
(17, 'BRANDNEW'), (17, 'AGILE'),
(18, 'DEMOCRACY'), (18, 'AGILE'),
(19, 'RULE'), (19, 'LEADER'),
(20, 'FORMAL'), (20, 'LEADER'),
(21, 'COMFY'), (21, 'BRANDNEW'),
(22, 'RULE'), (22, 'LEADER'),
(23, 'COMFY'), (23, 'DEMOCRACY'),
(24, 'BRANDNEW'), (24, 'AGILE'),
(25, 'DEMOCRACY'), (25, 'AGILE'),
(26, 'COMFY'), (26, 'BRANDNEW'),
(27, 'RULE'), (27, 'LEADER'),
(28, 'BRANDNEW'), (28, 'AGILE'),
(29, 'COMFY'), (29, 'DEMOCRACY'),
(30, 'FORMAL'), (30, 'LEADER'),

-- 팀이 없는 후보자들 (31-100)
(31, 'RULE'), (31, 'LEADER'),
(32, 'COMFY'), (32, 'DEMOCRACY'),
(33, 'BRANDNEW'), (33, 'AGILE'),
(34, 'COMFY'), (34, 'DEMOCRACY'),
(35, 'FORMAL'), (35, 'LEADER'),
(36, 'RULE'), (36, 'LEADER'),
(37, 'COMFY'), (37, 'DEMOCRACY'),
(38, 'BRANDNEW'), (38, 'AGILE'),
(39, 'COMFY'), (39, 'DEMOCRACY'),
(40, 'FORMAL'), (40, 'LEADER'),
(41, 'DEMOCRACY'), (41, 'AGILE'),
(42, 'COMFY'), (42, 'DEMOCRACY'),
(43, 'RULE'), (43, 'LEADER'),
(44, 'BRANDNEW'), (44, 'AGILE'),
(45, 'FORMAL'), (45, 'LEADER'),
(46, 'BRANDNEW'), (46, 'AGILE'),
(47, 'RULE'), (47, 'LEADER'),
(48, 'COMFY'), (48, 'DEMOCRACY'),
(49, 'BRANDNEW'), (49, 'AGILE'),
(50, 'COMFY'), (50, 'DEMOCRACY'),
(51, 'COMFY'), (51, 'DEMOCRACY'),
(52, 'BRANDNEW'), (52, 'AGILE'),
(53, 'COMFY'), (53, 'DEMOCRACY'),
(54, 'RULE'), (54, 'LEADER'),
(55, 'BRANDNEW'), (55, 'AGILE'),
(56, 'FORMAL'), (56, 'LEADER'),
(57, 'RULE'), (57, 'LEADER'),
(58, 'DEMOCRACY'), (58, 'AGILE'),
(59, 'COMFY'), (59, 'DEMOCRACY'),
(60, 'BRANDNEW'), (60, 'AGILE'),
(61, 'RULE'), (61, 'LEADER'),
(62, 'COMFY'), (62, 'DEMOCRACY'),
(63, 'FORMAL'), (63, 'LEADER'),
(64, 'RULE'), (64, 'LEADER'),
(65, 'BRANDNEW'), (65, 'AGILE'),
(66, 'DEMOCRACY'), (66, 'AGILE'),
(67, 'BRANDNEW'), (67, 'AGILE'),
(68, 'COMFY'), (68, 'DEMOCRACY'),
(69, 'COMFY'), (69, 'DEMOCRACY'),
(70, 'RULE'), (70, 'LEADER'),
(71, 'BRANDNEW'), (71, 'AGILE'),
(72, 'RULE'), (72, 'LEADER'),
(73, 'COMFY'), (73, 'DEMOCRACY'),
(74, 'BRANDNEW'), (74, 'AGILE'),
(75, 'RULE'), (75, 'LEADER'),
(76, 'COMFY'), (76, 'DEMOCRACY'),
(77, 'BRANDNEW'), (77, 'AGILE'),
(78, 'DEMOCRACY'), (78, 'AGILE'),
(79, 'RULE'), (79, 'LEADER'),
(80, 'FORMAL'), (80, 'LEADER'),
(81, 'COMFY'), (81, 'DEMOCRACY'),
(82, 'BRANDNEW'), (82, 'AGILE'),
(83, 'RULE'), (83, 'LEADER'),
(84, 'COMFY'), (84, 'DEMOCRACY'),
(85, 'BRANDNEW'), (85, 'AGILE'),
(86, 'DEMOCRACY'), (86, 'AGILE'),
(87, 'RULE'), (87, 'LEADER'),
(88, 'FORMAL'), (88, 'LEADER'),
(89, 'COMFY'), (89, 'DEMOCRACY'),
(90, 'BRANDNEW'), (90, 'AGILE'),
(91, 'RULE'), (91, 'LEADER'),
(92, 'FORMAL'), (92, 'LEADER'),
(93, 'BRANDNEW'), (93, 'AGILE'),
(94, 'DEMOCRACY'), (94, 'AGILE'),
(95, 'COMFY'), (95, 'DEMOCRACY'),
(96, 'BRANDNEW'), (96, 'AGILE'),
(97, 'RULE'), (97, 'LEADER'),
(98, 'FORMAL'), (98, 'LEADER'),
(99, 'BRANDNEW'), (99, 'AGILE'),
(100, 'RULE'), (100, 'LEADER');

-- 팀 프로젝트 목표 (team_preference) - 25개 팀
INSERT INTO TEAM_TEAM_PREFERENCE (team_team_id, team_preference) VALUES
                                                                     (1, 'PORTFOLIO'), (1, 'STUDY'),
                                                                     (2, 'PROFESSIONAL'), (2, 'QUALITY'),
                                                                     (3, 'JOB'), (3, 'PROFESSIONAL'),
                                                                     (4, 'IDEA'), (4, 'AWARD'),
                                                                     (5, 'PORTFOLIO'), (5, 'IDEA'),
                                                                     (6, 'PORTFOLIO'), (6, 'JOB'),
                                                                     (7, 'PROFESSIONAL'), (7, 'AWARD'),
                                                                     (8, 'IDEA'), (8, 'PORTFOLIO'),
                                                                     (9, 'JOB'), (9, 'PROFESSIONAL'),
                                                                     (10, 'STUDY'), (10, 'IDEA'),
                                                                     (11, 'PORTFOLIO'), (11, 'JOB'),
                                                                     (12, 'STUDY'), (12, 'PORTFOLIO'),
                                                                     (13, 'PROFESSIONAL'), (13, 'QUALITY'),
                                                                     (14, 'IDEA'), (14, 'AWARD'),
                                                                     (15, 'PORTFOLIO'), (15, 'STUDY'),
                                                                     (16, 'PROFESSIONAL'), (16, 'QUALITY'),
                                                                     (17, 'AWARD'), (17, 'PROFESSIONAL'),
                                                                     (18, 'IDEA'), (18, 'PROFESSIONAL'),
                                                                     (19, 'PROFESSIONAL'), (19, 'AWARD'),
                                                                     (20, 'PROFESSIONAL'), (20, 'QUALITY'),
                                                                     (21, 'PORTFOLIO'), (21, 'IDEA'),
                                                                     (22, 'PROFESSIONAL'), (22, 'AWARD'),
                                                                     (23, 'STUDY'), (23, 'IDEA'),
                                                                     (24, 'PORTFOLIO'), (24, 'STUDY'),
                                                                     (25, 'PORTFOLIO'), (25, 'STUDY');

-- 팀 분위기 (team_vive) - 25개 팀
INSERT INTO TEAM_TEAM_VIVE (team_team_id, team_vive) VALUES
                                                         (1, 'COMFY'), (1, 'DEMOCRACY'),
                                                         (2, 'RULE'), (2, 'LEADER'),
                                                         (3, 'DEMOCRACY'), (3, 'AGILE'),
                                                         (4, 'BRANDNEW'), (4, 'AGILE'),
                                                         (5, 'COMFY'), (5, 'BRANDNEW'),
                                                         (6, 'COMFY'), (6, 'DEMOCRACY'),
                                                         (7, 'RULE'), (7, 'LEADER'),
                                                         (8, 'BRANDNEW'), (8, 'AGILE'),
                                                         (9, 'FORMAL'), (9, 'LEADER'),
                                                         (10, 'COMFY'), (10, 'BRANDNEW'),
                                                         (11, 'DEMOCRACY'), (11, 'AGILE'),
                                                         (12, 'COMFY'), (12, 'DEMOCRACY'),
                                                         (13, 'RULE'), (13, 'LEADER'),
                                                         (14, 'BRANDNEW'), (14, 'AGILE'),
                                                         (15, 'COMFY'), (15, 'DEMOCRACY'),
                                                         (16, 'RULE'), (16, 'LEADER'),
                                                         (17, 'BRANDNEW'), (17, 'AGILE'),
                                                         (18, 'DEMOCRACY'), (18, 'AGILE'),
                                                         (19, 'RULE'), (19, 'LEADER'),
                                                         (20, 'FORMAL'), (20, 'LEADER'),
                                                         (21, 'COMFY'), (21, 'BRANDNEW'),
                                                         (22, 'RULE'), (22, 'LEADER'),
                                                         (23, 'COMFY'), (23, 'DEMOCRACY'),
                                                         (24, 'BRANDNEW'), (24, 'AGILE'),
                                                         (25, 'DEMOCRACY'), (25, 'AGILE');

-- 팀 리더 설정 (일부 팀은 리더 없음)
UPDATE team SET leader_id = 1 WHERE team_id = 1;
UPDATE team SET leader_id = 3 WHERE team_id = 2;
UPDATE team SET leader_id = 5 WHERE team_id = 3;
UPDATE team SET leader_id = 26 WHERE team_id = 4;
UPDATE team SET leader_id = 27 WHERE team_id = 5;
UPDATE team SET leader_id = 6 WHERE team_id = 6;
UPDATE team SET leader_id = 7 WHERE team_id = 7;
UPDATE team SET leader_id = 8 WHERE team_id = 8;
UPDATE team SET leader_id = 9 WHERE team_id = 9;
UPDATE team SET leader_id = 10 WHERE team_id = 10;
UPDATE team SET leader_id = 11 WHERE team_id = 11;
UPDATE team SET leader_id = 12 WHERE team_id = 12;
UPDATE team SET leader_id = 13 WHERE team_id = 13;
UPDATE team SET leader_id = 14 WHERE team_id = 14;
UPDATE team SET leader_id = 15 WHERE team_id = 15;
UPDATE team SET leader_id = 16 WHERE team_id = 16;
UPDATE team SET leader_id = 17 WHERE team_id = 17;
UPDATE team SET leader_id = 18 WHERE team_id = 18;
UPDATE team SET leader_id = 19 WHERE team_id = 19;
UPDATE team SET leader_id = 20 WHERE team_id = 20;
UPDATE team SET leader_id = 21 WHERE team_id = 21;
UPDATE team SET leader_id = 22 WHERE team_id = 22;
UPDATE team SET leader_id = 23 WHERE team_id = 23;
UPDATE team SET leader_id = 24 WHERE team_id = 24;
UPDATE team SET leader_id = 25 WHERE team_id = 25;