-- 팀 테이블 먼저 생성 (User 테이블이 Team을 참조하므로)
INSERT INTO team (team_name, backend_count, frontend_count, ai_count, pm_count, design_count, team_domain, member_wanted, team_description, status) VALUES
                                                                                                                                                        ('웹서비스 개발팀', 1, 2, 0, 1, 1, 'Web Development', 'FRONTEND,DESIGN', '사용자 친화적인 웹 서비스를 개발하는 팀입니다.', 'UNLOCKED'),
                                                                                                                                                        ('AI 플랫폼팀', 2, 1, 2, 1, 0, 'AI/ML', 'AI,BACKEND', '머신러닝 기반 플랫폼을 구축하는 팀입니다.', 'UNLOCKED'),
                                                                                                                                                        ('모바일 앱팀', 1, 2, 0, 1, 1, 'Mobile', 'FRONTEND,PM', 'React Native를 활용한 모바일 앱 개발팀입니다.', 'UNLOCKED'),
                                                                                                                                                        ('핀테크 서비스팀', 2, 1, 1, 1, 1, 'Fintech', 'BACKEND,AI', '금융 서비스 플랫폼을 개발하는 팀입니다.', 'UNLOCKED'),
                                                                                                                                                        ('게임 개발팀', 1, 2, 0, 0, 2, 'Game', 'FRONTEND,DESIGN', '인디 게임을 개발하는 창의적인 팀입니다.', 'UNLOCKED'),
                                                                                                                                                        ('EdTech 스타트업', 1, 1, 1, 1, 1, 'Education', 'AI,PM', '교육용 AI 플랫폼을 개발하는 팀입니다.', 'UNLOCKED'),
                                                                                                                                                        ('이커머스팀', 2, 2, 0, 1, 1, 'E-commerce', 'BACKEND,FRONTEND', '온라인 쇼핑몰 플랫폼을 구축하는 팀입니다.', 'UNLOCKED'),
                                                                                                                                                        ('헬스케어 솔루션', 1, 1, 2, 1, 0, 'Healthcare', 'AI,DESIGN', '의료 데이터 분석 플랫폼을 개발하는 팀입니다.', 'UNLOCKED'),
                                                                                                                                                        ('소셜미디어팀', 1, 2, 1, 1, 1, 'Social Media', 'FRONTEND,AI', 'SNS 플랫폼을 개발하는 팀입니다.', 'UNLOCKED'),
                                                                                                                                                        ('IoT 솔루션팀', 2, 1, 1, 1, 0, 'IoT', 'BACKEND,AI', 'IoT 기기 제어 플랫폼을 개발하는 팀입니다.', 'UNLOCKED'),
                                                                                                                                                        ('블록체인팀', 2, 1, 0, 1, 1, 'Blockchain', 'BACKEND,DESIGN', 'DeFi 서비스를 개발하는 팀입니다.', 'UNLOCKED'),
                                                                                                                                                        ('데이터 분석팀', 1, 1, 2, 1, 1, 'Data Analytics', 'AI,BACKEND', '빅데이터 분석 대시보드를 개발하는 팀입니다.', 'UNLOCKED'),
                                                                                                                                                        ('스마트시티팀', 2, 1, 1, 1, 1, 'Smart City', 'BACKEND,AI', '도시 관리 시스템을 개발하는 팀입니다.', 'UNLOCKED'),
                                                                                                                                                        ('미디어 플랫폼팀', 1, 2, 1, 1, 2, 'Media', 'FRONTEND,DESIGN', '동영상 스트리밍 플랫폼을 개발하는 팀입니다.', 'UNLOCKED'),
                                                                                                                                                        ('보안 솔루션팀', 3, 1, 1, 1, 0, 'Security', 'BACKEND,AI', '사이버 보안 플랫폼을 개발하는 팀입니다.', 'UNLOCKED');
-- 사용자 테이블 (팀에 속한 40명 + 팀 없는 60명)
INSERT INTO USERS (role, team_id, user_status, user_name, user_email, major, last_class, user_profile, project_experience, qualification) VALUES
-- 팀 1: 웹서비스 개발팀 (3명)
('student', 1, 'IN_TEAM', '김철수', 'kimcs@example.com', true, 4, 'React와 Spring을 활용한 풀스택 개발자를 꿈꾸고 있습니다.', 'React 쇼핑몰 프로젝트, Spring Boot REST API 개발', '정보처리기사'),
('student', 1, 'IN_TEAM', '이영희', 'leeyh@example.com', true, 3, 'UX/UI 디자인과 프론트엔드 개발에 관심이 많습니다.', 'Figma를 활용한 웹 디자인, React 컴포넌트 개발', 'GTQ 1급'),
('student', 1, 'IN_TEAM', '박민준', 'parkmin@example.com', false, 2, '프로젝트 매니징과 기획에 특화된 학생입니다.', '동아리 프로젝트 기획 및 관리, 스타트업 인턴 경험', 'PMP 자격증'),
-- 팀 2: AI 플랫폼팀 (3명)
('student', 2, 'IN_TEAM', '최준호', 'choijh@example.com', true, 4, '머신러닝과 백엔드 개발을 전문으로 하는 학생입니다.', 'Python Django 웹앱 개발, TensorFlow 모델 구축', '정보처리기사'),
('student', 2, 'IN_TEAM', '정수진', 'jungsj@example.com', true, 3, '데이터 사이언스와 AI 모델링에 관심이 많습니다.', 'Kaggle 대회 참여, CNN 이미지 분류 프로젝트', 'ADsP'),
('student', 2, 'IN_TEAM', '강지원', 'kangjw@example.com', false, 2, 'AI 서비스 기획과 PM 역할에 관심있는 학생입니다.', 'AI 스타트업 기획 인턴, 프로덕트 매니지먼트 스터디', 'SQLD'),
-- 팀 3: 모바일 앱팀 (3명)
('student', 3, 'IN_TEAM', '윤서연', 'yoonsy@example.com', true, 4, 'React Native를 활용한 모바일 개발자입니다.', 'React Native 날씨앱, Flutter 투두리스트 앱', 'OCJP'),
('student', 3, 'IN_TEAM', '임태현', 'limth@example.com', true, 3, '모바일 UI/UX와 프론트엔드 개발을 담당합니다.', 'Swift iOS 앱 개발, React 웹앱 개발', '정보기기운용기능사'),
('student', 3, 'IN_TEAM', '서지훈', 'seojh@example.com', false, 2, '모바일 프로젝트 매니징에 관심있는 학생입니다.', '앱 기획 경험, 애자일 방법론 스터디', 'SQLD'),
-- 팀 4: 핀테크 서비스팀 (3명)
('student', 4, 'IN_TEAM', '송민석', 'songms@example.com', true, 4, '금융 도메인의 백엔드 개발자를 목표로 합니다.', 'Spring Security 인증 시스템, MySQL 데이터베이스 설계', '정보처리기사'),
('student', 4, 'IN_TEAM', '한예슬', 'hanys@example.com', true, 3, '핀테크 서비스의 프론트엔드를 담당합니다.', 'Vue.js SPA 개발, 결제 모듈 연동 경험', 'SQLD'),
('student', 4, 'IN_TEAM', '조현우', 'johw@example.com', false, 2, '금융 데이터 분석과 AI 모델링을 담당합니다.', '주식 예측 모델 개발, 금융 데이터 크롤링', 'ADsP'),
-- 팀 5: 게임 개발팀 (3명)
('student', 5, 'IN_TEAM', '배성호', 'baesh@example.com', true, 4, 'Unity와 웹 게임 개발에 특화된 개발자입니다.', 'Unity 2D 게임 개발, React 미니게임 제작', 'Unity 인증'),
('student', 5, 'IN_TEAM', '신유진', 'shinyj@example.com', true, 3, '게임 UI/UX 디자인과 그래픽 작업을 담당합니다.', '게임 캐릭터 디자인, UI 애니메이션 제작', 'GTQ 1급'),
('student', 5, 'IN_TEAM', '장혜림', 'janghl@example.com', true, 2, '게임 아트와 그래픽 디자인에 관심있는 학생입니다.', '2D 아트 제작, 게임 UI 디자인', 'GTQ 2급'),
-- 팀 6: EdTech 스타트업 (3명)
('student', 6, 'IN_TEAM', '홍길동', 'honggd@example.com', true, 4, '교육용 웹 플랫폼 개발자입니다.', 'Django 학습관리시스템, React 온라인 강의 플랫폼', '정보처리기사'),
('student', 6, 'IN_TEAM', '김민지', 'kimmj@example.com', true, 3, '교육 콘텐츠 AI와 NLP 연구를 합니다.', 'BERT 기반 문서 분류, 교육용 챗봇 개발', 'TOEIC 900'),
('student', 6, 'IN_TEAM', '이준서', 'leejs@example.com', false, 2, 'EdTech 서비스 기획과 사용자 리서치를 담당합니다.', '사용자 인터뷰 경험, 서비스 기획 포트폴리오', 'GAIQ'),
-- 팀 7: 이커머스팀 (3명)
('student', 7, 'IN_TEAM', '오지훈', 'ohjh@example.com', true, 4, '대용량 트래픽을 처리하는 백엔드 개발자입니다.', 'Spring Boot MSA 구조, Redis 캐싱 적용', 'AWS SAA'),
('student', 7, 'IN_TEAM', '장서윤', 'jangsy@example.com', true, 3, '이커머스 UI/UX와 프론트엔드를 담당합니다.', 'Next.js 쇼핑몰, 결제 시스템 프론트 개발', 'SQLD'),
('student', 7, 'IN_TEAM', '김성민', 'kimsm@example.com', true, 2, '백엔드 개발에 관심있는 주니어 개발자입니다.', 'Spring Boot 기초 프로젝트, MySQL 데이터베이스 설계', '없음'),
-- 팀 8: 헬스케어 솔루션 (3명)
('student', 8, 'IN_TEAM', '노준혁', 'nojh@example.com', true, 4, '의료 데이터 분석과 AI 모델링을 전문으로 합니다.', '의료영상 분석 CNN 모델, Python 데이터 파이프라인', 'ADsP'),
('student', 8, 'IN_TEAM', '서미래', 'seoml@example.com', true, 3, '헬스케어 서비스의 백엔드 API를 담당합니다.', 'FastAPI 의료 데이터 API, PostgreSQL 설계', 'SQLD'),
('student', 8, 'IN_TEAM', '정다은', 'jungde@example.com', true, 2, 'AI와 데이터 분석에 관심있는 학생입니다.', 'Python 기초, 머신러닝 스터디', '없음'),
-- 팀 9: 소셜미디어팀 (3명)
('student', 9, 'IN_TEAM', '고은별', 'goeb@example.com', true, 4, '소셜 미디어 플랫폼의 백엔드를 개발합니다.', 'Node.js SNS API, WebSocket 실시간 채팅', '정보처리기사'),
('student', 9, 'IN_TEAM', '안지현', 'anjh@example.com', true, 3, '소셜미디어 추천 알고리즘을 개발합니다.', '추천시스템 개발, 자연어처리 감정분석', 'ADsP'),
('student', 9, 'IN_TEAM', '최원석', 'choiws@example.com', true, 2, '프론트엔드 개발에 관심있는 학생입니다.', 'React 기초, JavaScript ES6', '없음'),
-- 팀 10: IoT 솔루션팀 (3명)
('student', 10, 'IN_TEAM', '문정호', 'moonjh@example.com', true, 4, 'IoT 기기와 통신하는 백엔드 시스템을 개발합니다.', 'MQTT 프로토콜 활용, Arduino 센서 데이터 수집', '정보처리기사'),
('student', 10, 'IN_TEAM', '허윤아', 'heoya@example.com', true, 3, 'IoT 데이터 분석과 예측 모델을 담당합니다.', '시계열 데이터 분석, LSTM 예측 모델', 'ADsP'),
('student', 10, 'IN_TEAM', '박준영', 'parkjy@example.com', true, 2, '백엔드 개발과 IoT에 관심있는 학생입니다.', 'Node.js 기초, 라즈베리파이 프로젝트', '없음'),
-- 팀 11: 블록체인팀 (2명)
('student', 11, 'IN_TEAM', '유재석', 'yujs@example.com', true, 4, '블록체인 DApp 백엔드 개발자입니다.', 'Solidity 스마트 컨트랙트, Web3.js 연동', '정보보안기사'),
('student', 11, 'IN_TEAM', '김태리', 'kimtr@example.com', true, 3, '블록체인 서비스의 프론트엔드를 담당합니다.', 'React Web3 DApp, MetaMask 연동', 'SQLD'),
-- 팀 12: 데이터 분석팀 (2명)
('student', 12, 'IN_TEAM', '박서준', 'parksj@example.com', true, 4, '빅데이터 분석과 시각화를 전문으로 합니다.', 'Python 데이터 분석, D3.js 시각화', 'ADsP'),
('student', 12, 'IN_TEAM', '전지현', 'jeonjh@example.com', true, 3, '데이터 파이프라인과 ML 모델을 개발합니다.', 'Apache Kafka 스트리밍, MLflow 모델 관리', 'SQLD'),
-- 팀 13: 스마트시티팀 (2명)
('student', 13, 'IN_TEAM', '이병헌', 'leebh@example.com', true, 4, '도시 데이터를 처리하는 백엔드를 개발합니다.', 'Spring Cloud MSA, Elasticsearch 로그 분석', 'AWS SAA'),
('student', 13, 'IN_TEAM', '송혜교', 'songhg@example.com', true, 3, '스마트시티 AI 모델과 분석을 담당합니다.', '도시 교통 예측 모델, GIS 데이터 분석', 'ADsP'),
-- 팀 14: 미디어 플랫폼팀 (2명)
('student', 14, 'IN_TEAM', '현빈', 'hyunbin@example.com', true, 4, '동영상 스트리밍 백엔드를 개발합니다.', 'FFmpeg 동영상 처리, CDN 연동', '정보처리기사'),
('student', 14, 'IN_TEAM', '손예진', 'sonyj@example.com', true, 3, '미디어 플랫폼의 프론트엔드를 담당합니다.', 'React 비디오 플레이어, 반응형 웹 디자인', 'GTQ 1급'),
-- 팀 15: 보안 솔루션팀 (2명)
('student', 15, 'IN_TEAM', '류준열', 'ryujy@example.com', true, 4, '보안 시스템의 백엔드를 개발합니다.', '암호화 시스템 구현, 침입탐지 시스템', '정보보안기사'),
('student', 15, 'IN_TEAM', '정유미', 'jeongym@example.com', true, 3, '보안 로그 분석과 AI 탐지 모델을 개발합니다.', '이상탐지 모델링, 로그 분석 자동화', 'ADsP'),

-- 팀 없는 사용자들 (60명)
('student', null, 'WAITING', '강동원', 'kangdw@example.com', true, 4, 'Java Spring 백엔드 개발에 특화되어 있습니다.', 'Spring Boot 쇼핑몰, JPA 최적화 프로젝트', '정보처리기사'),
('student', null, 'WAITING', '조인성', 'joins@example.com', true, 3, 'React와 TypeScript 프론트엔드 개발자입니다.', 'TypeScript React 프로젝트, Redux 상태관리', 'SQLD'),
('student', null, 'INACTIVE', '김고은', 'kimge@example.com', true, 2, 'UI/UX 디자인과 퍼블리싱에 관심있습니다.', 'Figma 디자인, HTML/CSS 반응형 웹', 'GTQ 1급'),
('student', null, 'WAITING', '박보영', 'parkby@example.com', false, 4, '프로젝트 매니징과 비즈니스 기획을 담당합니다.', '스타트업 PM 인턴, 애자일 스크럼 경험', 'PMP'),
('student', null, 'WAITING', '이동욱', 'leedw@example.com', true, 3, 'Python Django와 데이터 분석에 특화되어 있습니다.', 'Django REST API, Pandas 데이터 분석', 'ADsP'),
('student', null, 'WAITING', '김태희', 'kimth@example.com', true, 4, 'AI 머신러닝 모델 개발자입니다.', 'TensorFlow 이미지 분류, NLP 감정분석', 'TOEIC 850'),
('student', null, 'INACTIVE', '원빈', 'wonbin@example.com', true, 2, '모바일 앱 개발에 관심있는 초보 개발자입니다.', 'Flutter 기초 프로젝트, Kotlin 안드로이드', '없음'),
('student', null, 'WAITING', '전지현', 'jeonjh2@example.com', true, 3, 'Vue.js 프론트엔드와 디자인을 담당합니다.', 'Vue.js SPA, Adobe XD 디자인', 'GTQ 2급'),
('student', null, 'WAITING', '정우성', 'jeongws@example.com', true, 4, 'Node.js 백엔드와 DevOps에 관심있습니다.', 'Express REST API, Docker 컨테이너화', 'AWS CCP'),
('student', null, 'WAITING', '한지민', 'hanjm@example.com', true, 3, 'React Native 모바일 개발자입니다.', 'React Native 투두앱, Firebase 연동', 'OCJP'),
('student', null, 'INACTIVE', '송강호', 'songkh@example.com', false, 4, '게임 기획과 PM 역할에 관심있습니다.', '게임 기획서 작성, Unity 게임 제작 참여', '없음'),
('student', null, 'WAITING', '김혜수', 'kimhs@example.com', true, 3, '데이터 시각화와 분석 도구 개발자입니다.', 'D3.js 대시보드, Python 시각화', 'SQLD'),
('student', null, 'WAITING', '이정재', 'leejj@example.com', true, 4, 'Spring Security와 인증 시스템 전문가입니다.', 'OAuth2 인증, JWT 토큰 관리', '정보보안기사'),
('student', null, 'WAITING', '김유정', 'kimyj@example.com', true, 2, 'HTML/CSS/JS 기초 웹 개발자입니다.', 'JavaScript 바닐라 프로젝트, Bootstrap 반응형', '웹디자인기능사'),
('student', null, 'INACTIVE', '황정민', 'hwangjm@example.com', true, 4, 'AI 컴퓨터 비전 연구에 관심있습니다.', 'OpenCV 영상처리, CNN 객체인식', 'TOEIC 750'),
('student', null, 'WAITING', '수지', 'suzy@example.com', true, 3, 'UX 리서치와 프로덕트 디자인을 담당합니다.', '사용자 인터뷰, 프로토타이핑', 'UXUI 수료증'),
('student', null, 'WAITING', '공유', 'gongyoo@example.com', true, 4, 'MSA 아키텍처와 백엔드 최적화 전문가입니다.', 'Spring Cloud Gateway, Redis 캐싱', 'AWS SAA'),
('student', null, 'WAITING', '아이유', 'iu@example.com', true, 3, 'React와 웹 접근성에 관심있는 개발자입니다.', 'React Hook 활용, 웹 접근성 준수', 'SQLD'),
('student', null, 'INACTIVE', '차태현', 'chath@example.com', false, 2, '스타트업 기획과 마케팅에 관심있습니다.', '스타트업 창업동아리, 디지털마케팅 스터디', 'GAIQ'),
('student', null, 'WAITING', '한효주', 'hanhj@example.com', true, 3, 'Python Flask와 API 개발에 특화되어 있습니다.', 'Flask REST API, SQLAlchemy ORM', 'SQLD'),
('student', null, 'WAITING', '유재석', 'yujs2@example.com', true, 4, 'GraphQL과 모던 백엔드 기술스택 개발자입니다.', 'GraphQL Apollo Server, MongoDB', '정보처리기사'),
('student', null, 'WAITING', '박나래', 'parknr@example.com', true, 3, 'Angular와 TypeScript 프론트엔드 개발자입니다.', 'Angular 관리자페이지, RxJS 상태관리', 'SQLD'),
('student', null, 'INACTIVE', '김종국', 'kimjk@example.com', true, 4, 'DevOps와 인프라 자동화에 관심있습니다.', 'Terraform IaC, Jenkins CI/CD', 'AWS DevOps'),
('student', null, 'WAITING', '송지효', 'songjh@example.com', true, 2, 'Svelte와 모던 프론트엔드 기술에 관심있습니다.', 'Svelte 컴포넌트, Vite 빌드도구', '없음'),
('student', null, 'WAITING', '하하', 'haha@example.com', true, 3, 'Go 언어와 마이크로서비스 개발자입니다.', 'Go Gin 웹프레임워크, gRPC 통신', 'AWS CCP'),
('student', null, 'WAITING', '전소민', 'jeonsm@example.com', true, 4, 'Kotlin과 안드로이드 네이티브 앱 개발자입니다.', 'Kotlin 안드로이드 앱, Room 데이터베이스', 'SQLD'),
('student', null, 'INACTIVE', '양세찬', 'yangsc@example.com', false, 3, '블록체인과 Web3 기술에 관심있습니다.', 'Solidity 기초, DeFi 프로토콜 연구', '없음'),
('student', null, 'WAITING', '지석진', 'jisj@example.com', true, 4, 'Rust와 시스템 프로그래밍에 특화되어 있습니다.', 'Rust 웹서버, WebAssembly 모듈', '정보처리기사'),
('student', null, 'WAITING', '김하늘', 'kimhn@example.com', true, 3, 'Next.js와 SSR 웹 개발에 관심있습니다.', 'Next.js 블로그, Vercel 배포', 'SQLD'),
('student', null, 'WAITING', '전도연', 'jeondo@example.com', true, 4, '자연어처리와 NLP AI 모델 개발자입니다.', 'BERT 파인튜닝, 텍스트 분류 모델', 'ADsP'),
('student', null, 'INACTIVE', '박해일', 'parkhi@example.com', true, 2, '게임 서버와 실시간 통신에 관심있습니다.', 'Socket.io 실시간 게임, Unity 네트워킹', '없음'),
('student', null, 'WAITING', '김희애', 'kimha@example.com', true, 3, 'PHP Laravel과 웹 서비스 개발자입니다.', 'Laravel API 개발, MySQL 설계', 'SQLD'),
('student', null, 'WAITING', '조정석', 'jojs@example.com', true, 4, '.NET Core와 C# 백엔드 개발자입니다.', 'ASP.NET Core API, Entity Framework', 'MCP'),
('student', null, 'WAITING', '정려원', 'jeonglw@example.com', true, 3, 'Vue.js 3와 Composition API 전문가입니다.', 'Vue3 Composition API, Vuex 상태관리', 'SQLD'),
('student', null, 'INACTIVE', '오달수', 'ohds@example.com', false, 4, '엔터테인먼트 서비스 기획에 관심있습니다.', 'OTT 서비스 기획, 콘텐츠 큐레이션', '없음'),
('student', null, 'WAITING', '김선아', 'kimsa@example.com', true, 3, 'Ruby on Rails와 웹 애플리케이션 개발자입니다.', 'Rails API 서버, PostgreSQL 최적화', 'SQLD'),
('student', null, 'WAITING', '류승범', 'ryusb@example.com', true, 4, 'Elasticsearch와 검색 엔진 전문가입니다.', 'Elasticsearch 클러스터, 검색 최적화', 'AWS SAA'),
('student', null, 'WAITING', '문소리', 'moonsl@example.com', true, 3, 'Scala와 함수형 프로그래밍 개발자입니다.', 'Scala Play Framework, Akka 액터모델', 'SQLD'),
('student', null, 'INACTIVE', '설경구', 'seolkg@example.com', true, 2, '보안과 해킹 방어에 관심있는 초보자입니다.', 'Kali Linux, 웹 보안 기초', '없음'),
('student', null, 'WAITING', '김희선', 'kimhs2@example.com', true, 3, 'Django Rest Framework API 개발자입니다.', 'DRF API 서버, Celery 비동기 작업', 'ADsP'),
('student', null, 'WAITING', '최민식', 'choims@example.com', true, 4, 'TensorFlow와 딥러닝 모델 최적화 전문가입니다.', 'TensorFlow Serving, 모델 경량화', 'ADsP'),
('student', null, 'WAITING', '전지현', 'jeonjh3@example.com', true, 3, 'Figma와 프로토타이핑 디자이너입니다.', 'Figma 디자인시스템, 인터랙션 디자인', 'GTQ 1급'),
('student', null, 'INACTIVE', '이병헌', 'leebh2@example.com', false, 2, '스타트업 투자와 비즈니스 모델에 관심있습니다.', '창업동아리 회계, 비즈니스모델 연구', '없음'),
('student', null, 'WAITING', '한석규', 'hansg@example.com', true, 4, 'Kafka와 이벤트 스트리밍 아키텍처 개발자입니다.', 'Apache Kafka, 실시간 데이터 파이프라인', 'AWS SAA'),
('student', null, 'WAITING', '김윤석', 'kimys@example.com', true, 3, 'Redux Toolkit과 React 상태관리 전문가입니다.', 'Redux Toolkit, React Query', 'SQLD'),
('student', null, 'WAITING', '조여정', 'joyj@example.com', true, 4, 'Swift와 iOS 네이티브 앱 개발자입니다.', 'Swift UIKit, Core Data', 'iOS 개발자'),
('student', null, 'INACTIVE', '마동석', 'mads@example.com', true, 2, '게임 개발과 Unity 엔진에 관심있습니다.', 'Unity 3D 게임, C# 스크립팅', '없음'),
('student', null, 'WAITING', '김혜수', 'kimhs3@example.com', true, 3, 'Pandas와 데이터 전처리 전문가입니다.', 'Pandas 데이터 분석, Jupyter Notebook', 'ADsP'),
('student', null, 'WAITING', '황정민', 'hwangjm2@example.com', true, 4, 'Prometheus와 모니터링 시스템 개발자입니다.', 'Prometheus Grafana, 시스템 모니터링', 'AWS DevOps'),
('student', null, 'WAITING', '전도연', 'jeondo2@example.com', true, 3, 'Selenium과 테스트 자동화 개발자입니다.', 'Selenium WebDriver, 테스트 코드 작성', 'ISTQB'),
('student', null, 'INACTIVE', '김윤진', 'kimyj2@example.com', false, 4, '헬스케어 서비스 기획에 관심있습니다.', '의료 서비스 기획, 사용자 리서치', '없음'),
('student', null, 'WAITING', '박찬욱', 'parkcw@example.com', true, 3, 'Three.js와 WebGL 3D 웹 개발자입니다.', 'Three.js 3D 시각화, WebGL 셰이더', 'SQLD'),
('student', null, 'WAITING', '김태리', 'kimtr2@example.com', true, 4, 'FastAPI와 비동기 Python 백엔드 개발자입니다.', 'FastAPI 비동기 API, Pydantic 데이터 검증', 'AWS CCP'),
('student', null, 'WAITING', '정우성', 'jeongws2@example.com', true, 2, 'HTML Canvas와 웹 그래픽 프로그래밍 초보자입니다.', 'Canvas 2D 게임, 웹 애니메이션', '없음'),
('student', null, 'INACTIVE', '송강호', 'songkh2@example.com', true, 3, 'AR/VR과 메타버스 기술에 관심있습니다.', 'Unity AR Foundation, WebXR 기초', '없음'),
('student', null, 'WAITING', '전지현', 'jeonjh4@example.com', true, 4, 'Nuxt.js와 Vue 생태계 전문가입니다.', 'Nuxt.js SSR, Vue 생태계', 'SQLD'),
('student', null, 'WAITING', '이정재', 'leejj2@example.com', true, 3, 'Docker Compose와 컨테이너 오케스트레이션 개발자입니다.', 'Docker Swarm, 컨테이너 최적화', 'AWS CCP'),
('student', null, 'WAITING', '박서준', 'parksj2@example.com', true, 4, 'Apache Spark와 빅데이터 처리 전문가입니다.', 'Spark SQL, 대용량 데이터 처리', 'ADsP'),
('student', null, 'INACTIVE', '김고은', 'kimge2@example.com', false, 2, '소셜벤처와 사회적 가치 창출에 관심있습니다.', '사회적 기업 인턴, 임팩트 비즈니스', '없음');

-- 팀 리더 설정 (각 팀의 첫 번째 멤버를 리더로 설정)
UPDATE team SET leader_id = 1 WHERE team_id = 1;
UPDATE team SET leader_id = 4 WHERE team_id = 2;
UPDATE team SET leader_id = 7 WHERE team_id = 3;
UPDATE team SET leader_id = 10 WHERE team_id = 4;
UPDATE team SET leader_id = 13 WHERE team_id = 5;
UPDATE team SET leader_id = 16 WHERE team_id = 6;
UPDATE team SET leader_id = 19 WHERE team_id = 7;
UPDATE team SET leader_id = 22 WHERE team_id = 8;
UPDATE team SET leader_id = 25 WHERE team_id = 9;
UPDATE team SET leader_id = 28 WHERE team_id = 10;
UPDATE team SET leader_id = 31 WHERE team_id = 11;
UPDATE team SET leader_id = 33 WHERE team_id = 12;
UPDATE team SET leader_id = 35 WHERE team_id = 13;
UPDATE team SET leader_id = 37 WHERE team_id = 14;
UPDATE team SET leader_id = 39 WHERE team_id = 15;

-- 사용자별 희망 포지션 설정
INSERT INTO USER_WANTED_POSITION (USER_USER_ID, WANTED_POSITION) VALUES
-- 팀에 속한 사용자들 (1-40)
(1, 'BACKEND'), (1, 'FRONTEND'),
(2, 'FRONTEND'), (2, 'DESIGN'),
(3, 'PM'),
(4, 'BACKEND'), (4, 'AI'),
(5, 'AI'),
(6, 'PM'),
(7, 'FRONTEND'),
(8, 'PM'), (8, 'FRONTEND'),
(9, 'PM'),
(10, 'BACKEND'), (10, 'AI'),
(11, 'FRONTEND'),
(12, 'AI'),
(13, 'BACKEND'), (13, 'FRONTEND'),
(14, 'DESIGN'),
(15, 'DESIGN'),
(16, 'BACKEND'),
(17, 'AI'),
(18, 'PM'),
(19, 'BACKEND'),
(20, 'FRONTEND'),
(21, 'BACKEND'),
(22, 'AI'),
(23, 'BACKEND'),
(24, 'AI'),
(25, 'BACKEND'),
(26, 'FRONTEND'),
(27, 'FRONTEND'),
(28, 'BACKEND'),
(29, 'AI'),
(30, 'BACKEND'),
(31, 'BACKEND'),
(32, 'FRONTEND'),
(33, 'BACKEND'),
(34, 'FRONTEND'),
(35, 'BACKEND'),
(36, 'AI'),
(37, 'BACKEND'),
(38, 'FRONTEND'),
(39, 'BACKEND'),
(40, 'AI'),

-- 팀 없는 사용자들 (41-100)
(41, 'BACKEND'),
(42, 'FRONTEND'),
(43, 'DESIGN'),
(44, 'PM'),
(45, 'BACKEND'), (45, 'AI'),
(46, 'AI'),
(47, 'FRONTEND'),
(48, 'FRONTEND'), (48, 'DESIGN'),
(49, 'BACKEND'),
(50, 'FRONTEND'),
(51, 'PM'),
(52, 'AI'),
(53, 'BACKEND'),
(54, 'FRONTEND'),
(55, 'AI'),
(56, 'DESIGN'),
(57, 'BACKEND'),
(58, 'FRONTEND'),
(59, 'BACKEND'),
(60, 'FRONTEND'),
(61, 'BACKEND'),
(62, 'AI'),
(63, 'FRONTEND'),
(64, 'BACKEND'),
(65, 'PM'),
(66, 'BACKEND'),
(67, 'BACKEND'),
(68, 'FRONTEND'),
(69, 'BACKEND'),
(70, 'DESIGN'),
(71, 'BACKEND'),
(72, 'FRONTEND'),
(73, 'BACKEND'),
(74, 'FRONTEND'),
(75, 'AI'),
(76, 'BACKEND'),
(77, 'AI'),
(78, 'PM'),
(79, 'FRONTEND'),
(80, 'BACKEND'),
(81, 'FRONTEND'),
(82, 'AI'),
(83, 'FRONTEND'),
(84, 'BACKEND'),
(85, 'FRONTEND'),
(86, 'AI'),
(87, 'DESIGN'),
(88, 'BACKEND'),
(89, 'FRONTEND'),
(90, 'FRONTEND'),
(91, 'BACKEND'),
(92, 'FRONTEND'),
(93, 'FRONTEND'),
(94, 'BACKEND'),
(95, 'AI'),
(96, 'PM'),
(97, 'FRONTEND'),
(98, 'BACKEND'),
(99, 'PM');
-- 사용자별 기술 스택 설정
INSERT INTO USER_TECH_STACK (USER_USER_ID, TECH_STACK) VALUES
-- 팀에 속한 사용자들 (1-40)
(1, 'SPRING'), (1, 'JAVA'), (1, 'REACT'), (1, 'MYSQL'),
(2, 'REACT'), (2, 'TYPESCRIPT'), (2, 'CSS'),
(3, 'JAVASCRIPT'), (3, 'HTML'),
(4, 'SPRING'), (4, 'JAVA'), (4, 'PYTHON'), (4, 'TENSORFLOW'),
(5, 'PYTHON'), (5, 'TENSORFLOW'), (5, 'PYTORCH'), (5, 'SCIKIT_LEARN'),
(6, 'PYTHON'), (6, 'DJANGO'),
(7, 'REACT_NATIVE'), (7, 'JAVASCRIPT'), (7, 'FLUTTER'),
(8, 'REACT'), (8, 'TYPESCRIPT'), (8, 'SWIFT'),
(9, 'JAVASCRIPT'),
(10, 'SPRING'), (10, 'JAVA'), (10, 'MYSQL'), (10, 'REDIS'),
(11, 'VUE_JS'), (11, 'JAVASCRIPT'), (11, 'CSS'),
(12, 'PYTHON'), (12, 'TENSORFLOW'), (12, 'PYTORCH'),
(13, 'REACT'), (13, 'JAVASCRIPT'), (13, 'CSS'),
(14, 'CSS'),
(15, 'CSS'),
(16, 'SPRING'), (16, 'JAVA'), (16, 'PYTHON'), (16, 'DJANGO'),
(17, 'PYTHON'), (17, 'TENSORFLOW'), (17, 'OPENCV'),
(18, 'PYTHON'), (18, 'DJANGO'), (18, 'POSTGRESQL'),
(19, 'SPRING'), (19, 'JAVA'), (19, 'AWS'), (19, 'DOCKER'),
(20, 'NEXT_JS'), (20, 'REACT'), (20, 'TYPESCRIPT'),
(21, 'SPRING'), (21, 'JAVA'), (21, 'MYSQL'),
(22, 'PYTHON'), (22, 'TENSORFLOW'), (22, 'OPENCV'),
(23, 'SPRING'), (23, 'JAVA'), (23, 'POSTGRESQL'),
(24, 'PYTHON'), (24, 'TENSORFLOW'),
(25, 'NODE_JS'), (25, 'EXPRESS'), (25, 'JAVASCRIPT'),
(26, 'PYTHON'), (26, 'NLP'), (26, 'TENSORFLOW'),
(27, 'REACT'), (27, 'JAVASCRIPT'),
(28, 'NODE_JS'), (28, 'EXPRESS'), (28, 'MONGODB'),
(29, 'PYTHON'), (29, 'TENSORFLOW'), (29, 'PYTORCH'),
(30, 'NODE_JS'), (30, 'EXPRESS'),
(31, 'SPRING'), (31, 'JAVA'),
(32, 'REACT'), (32, 'JAVASCRIPT'),
(33, 'PYTHON'), (33, 'SCIKIT_LEARN'),
(34, 'PYTHON'), (34, 'TENSORFLOW'), (34, 'PYTORCH'),
(35, 'SPRING'), (35, 'JAVA'), (35, 'AWS'), (35, 'DOCKER'),
(36, 'PYTHON'), (36, 'TENSORFLOW'),
(37, 'SPRING'), (37, 'JAVA'),
(38, 'REACT'), (38, 'TYPESCRIPT'), (38, 'CSS'),
(39, 'SPRING'), (39, 'JAVA'),
(40, 'PYTHON'), (40, 'TENSORFLOW'),

-- 팀 없는 사용자들 (41-100)
(41, 'SPRING'), (41, 'JAVA'), (41, 'JPA'),
(42, 'REACT'), (42, 'TYPESCRIPT'), (42, 'REDUX'),
(43, 'HTML'), (43, 'CSS'),
(44, 'JAVASCRIPT'),
(45, 'PYTHON'), (45, 'DJANGO'),
(46, 'PYTHON'), (46, 'TENSORFLOW'), (46, 'NLP'),
(47, 'FLUTTER'), (47, 'KOTLIN'),
(48, 'VUE_JS'), (48, 'CSS'),
(49, 'NODE_JS'), (49, 'EXPRESS'), (49, 'DOCKER'),
(50, 'REACT_NATIVE'), (50, 'FIREBASE'),
(51, 'JAVASCRIPT'),
(52, 'PYTHON'),
(53, 'SPRING'), (53, 'JAVA'),
(54, 'JAVASCRIPT'), (54, 'HTML'), (54, 'CSS'),
(55, 'PYTHON'), (55, 'OPENCV'), (55, 'COMPUTER_VISION'),
(56, 'CSS'),
(57, 'SPRING'), (57, 'AWS'),
(58, 'REACT'),
(59, 'JAVASCRIPT'),
(60, 'PYTHON'), (60, 'FLASK'),
(61, 'NODE_JS'), (61, 'MONGODB'),
(62, 'ANGULAR'), (62, 'TYPESCRIPT'),
(63, 'DOCKER'), (63, 'JENKINS'),
(64, 'JAVASCRIPT'),
(65, 'GO'),
(66, 'KOTLIN'), (66, 'ANDROID'),
(67, 'JAVASCRIPT'),
(68, 'JAVA'),
(69, 'NEXT_JS'), (69, 'REACT'),
(70, 'PYTHON'), (70, 'NLP'),
(71, 'JAVASCRIPT'),
(72, 'PHP'), (72, 'MYSQL'),
(73, 'CSHARP'),
(74, 'VUE_JS'),
(75, 'JAVASCRIPT'),
(76, 'RUBY_ON_RAILS'), (76, 'POSTGRESQL'),
(77, 'ELASTICSEARCH'),
(78, 'JAVA'),
(79, 'PYTHON'),
(80, 'DJANGO'), (80, 'PYTHON'),
(81, 'TENSORFLOW'), (81, 'PYTHON'),
(82, 'CSS'),
(83, 'JAVASCRIPT'),
(84, 'PYTHON'),
(85, 'REACT'), (85, 'REDUX'),
(86, 'SWIFT'), (86, 'IOS'),
(87, 'JAVASCRIPT'),
(88, 'PYTHON'),
(89, 'PYTHON'),
(90, 'PYTHON'),
(91, 'JAVASCRIPT'),
(92, 'JAVASCRIPT'),
(93, 'PYTHON'),
(94, 'HTML'), (94, 'JAVASCRIPT'),
(95, 'JAVASCRIPT'),
(96, 'VUE_JS'),
(97, 'DOCKER'),
(98, 'PYTHON'),
(99, 'JAVASCRIPT');

-- 사용자별 프로젝트 목표 설정
INSERT INTO USER_PROJECT_GOAL (USER_USER_ID, PROJECT_PREFERENCE) VALUES
(1, 'JOB'), (1, 'PORTFOLIO'),
(2, 'PORTFOLIO'), (2, 'STUDY'),
(3, 'PROFESSIONAL'),
(4, 'JOB'), (4, 'AWARD'),
(5, 'STUDY'), (5, 'IDEA'),
(6, 'PROFESSIONAL'),
(7, 'PORTFOLIO'), (7, 'JOB'),
(8, 'STUDY'), (8, 'PORTFOLIO'),
(9, 'PROFESSIONAL'),
(10, 'JOB'), (10, 'PROFESSIONAL'),
(11, 'PORTFOLIO'), (11, 'STUDY'),
(12, 'STUDY'), (12, 'IDEA'),
(13, 'PORTFOLIO'), (13, 'QUICK'),
(14, 'PORTFOLIO'), (14, 'QUALITY'),
(15, 'PORTFOLIO'), (15, 'QUALITY'),
(16, 'JOB'), (16, 'PROFESSIONAL'),
(17, 'STUDY'), (17, 'AWARD'),
(18, 'PROFESSIONAL'), (18, 'JOB'),
(19, 'JOB'), (19, 'PORTFOLIO'),
(20, 'PORTFOLIO'), (20, 'STUDY'),
(21, 'JOB'), (21, 'PORTFOLIO'),
(22, 'STUDY'), (22, 'IDEA'),
(23, 'PROFESSIONAL'), (23, 'JOB'),
(24, 'STUDY'), (24, 'PORTFOLIO'),
(25, 'PORTFOLIO'), (25, 'QUICK'),
(26, 'STUDY'), (26, 'AWARD'),
(27, 'PORTFOLIO'), (27, 'STUDY'),
(28, 'JOB'), (28, 'PORTFOLIO'),
(29, 'STUDY'), (29, 'IDEA'),
(30, 'JOB'), (30, 'PORTFOLIO'),
(31, 'PROFESSIONAL'), (31, 'AWARD'),
(32, 'PORTFOLIO'), (32, 'STUDY'),
(33, 'STUDY'), (33, 'PROFESSIONAL'),
(34, 'AWARD'), (34, 'IDEA'),
(35, 'JOB'), (35, 'PROFESSIONAL'),
(36, 'STUDY'), (36, 'PORTFOLIO'),
(37, 'PORTFOLIO'), (37, 'QUICK'),
(38, 'STUDY'), (38, 'QUALITY'),
(39, 'PROFESSIONAL'), (39, 'JOB'),
(40, 'STUDY'), (40, 'AWARD'),
(41, 'JOB'), (41, 'PORTFOLIO'),
(42, 'PORTFOLIO'), (42, 'STUDY'),
(43, 'STUDY'), (43, 'PORTFOLIO'),
(44, 'PROFESSIONAL'), (44, 'JOB'),
(45, 'STUDY'), (45, 'PORTFOLIO'),
(46, 'AWARD'), (46, 'STUDY'),
(47, 'PORTFOLIO'), (47, 'STUDY'),
(48, 'PORTFOLIO'), (48, 'QUALITY'),
(49, 'JOB'), (49, 'PROFESSIONAL'),
(50, 'PORTFOLIO'), (50, 'STUDY'),
(51, 'IDEA'), (51, 'STUDY'),
(52, 'PROFESSIONAL'), (52, 'PORTFOLIO'),
(53, 'JOB'), (53, 'PROFESSIONAL'),
(54, 'STUDY'), (54, 'PORTFOLIO'),
(55, 'STUDY'), (55, 'AWARD'),
(56, 'PORTFOLIO'), (56, 'PROFESSIONAL'),
(57, 'JOB'), (57, 'PROFESSIONAL'),
(58, 'PORTFOLIO'), (58, 'STUDY'),
(59, 'IDEA'), (59, 'PROFESSIONAL'),
(60, 'PORTFOLIO'), (60, 'JOB'),
(61, 'STUDY'), (61, 'IDEA'),
(62, 'PORTFOLIO'), (62, 'PROFESSIONAL'),
(63, 'PROFESSIONAL'), (63, 'JOB'),
(64, 'STUDY'), (64, 'IDEA'),
(65, 'PROFESSIONAL'), (65, 'PORTFOLIO'),
(66, 'PORTFOLIO'), (66, 'JOB'),
(67, 'IDEA'), (67, 'STUDY'),
(68, 'STUDY'), (68, 'PROFESSIONAL'),
(69, 'PORTFOLIO'), (69, 'JOB'),
(70, 'STUDY'), (70, 'AWARD'),
(71, 'IDEA'), (71, 'STUDY'),
(72, 'PORTFOLIO'), (72, 'JOB'),
(73, 'PROFESSIONAL'), (73, 'PORTFOLIO'),
(74, 'STUDY'), (74, 'PORTFOLIO'),
(75, 'IDEA'), (75, 'PROFESSIONAL'),
(76, 'PORTFOLIO'), (76, 'JOB'),
(77, 'PROFESSIONAL'), (77, 'STUDY'),
(78, 'STUDY'), (78, 'IDEA'),
(79, 'PROFESSIONAL'), (79, 'STUDY'),
(80, 'PORTFOLIO'), (80, 'JOB'),
(81, 'STUDY'), (81, 'AWARD'),
(82, 'PORTFOLIO'), (82, 'PROFESSIONAL'),
(83, 'IDEA'), (83, 'PROFESSIONAL'),
(84, 'PROFESSIONAL'), (84, 'JOB'),
(85, 'PORTFOLIO'), (85, 'STUDY'),
(86, 'PORTFOLIO'), (86, 'JOB'),
(87, 'IDEA'), (87, 'STUDY'),
(88, 'STUDY'), (88, 'PORTFOLIO'),
(89, 'PROFESSIONAL'), (89, 'JOB'),
(90, 'PROFESSIONAL'), (90, 'PORTFOLIO'),
(91, 'IDEA'), (91, 'PROFESSIONAL'),
(92, 'STUDY'), (92, 'IDEA'),
(93, 'PORTFOLIO'), (93, 'JOB'),
(94, 'STUDY'), (94, 'PORTFOLIO'),
(95, 'IDEA'), (95, 'STUDY'),
(96, 'PORTFOLIO'), (96, 'PROFESSIONAL'),
(97, 'PROFESSIONAL'), (97, 'JOB'),
(98, 'STUDY'), (98, 'PROFESSIONAL'),
(99, 'PORTFOLIO'), (99, 'JOB');

-- 사용자별 프로젝트 분위기 설정
INSERT INTO USER_PROJECT_VIVE (USER_USER_ID, PERSONAL_PREFERENCE) VALUES
(1, 'FORMAL'), (1, 'RULE'),
(2, 'CASUAL'), (2, 'COMFY'),
(3, 'FORMAL'), (3, 'LEADER'),
(4, 'FORMAL'), (4, 'RULE'),
(5, 'CASUAL'), (5, 'DEMOCRACY'),
(6, 'FORMAL'), (6, 'LEADER'),
(7, 'CASUAL'), (7, 'AGILE'),
(8, 'CASUAL'), (8, 'COMFY'),
(9, 'FORMAL'), (9, 'LEADER'),
(10, 'FORMAL'), (10, 'WATERFALL'),
(11, 'CASUAL'), (11, 'DEMOCRACY'),
(12, 'CASUAL'), (12, 'BRANDNEW'),
(13, 'CASUAL'), (13, 'AGILE'),
(14, 'FORMAL'), (14, 'STABLE'),
(15, 'FORMAL'), (15, 'STABLE'),
(16, 'FORMAL'), (16, 'WATERFALL'),
(17, 'CASUAL'), (17, 'BRANDNEW'),
(18, 'FORMAL'), (18, 'RULE'),
(19, 'FORMAL'), (19, 'WATERFALL'),
(20, 'CASUAL'), (20, 'AGILE'),
(21, 'FORMAL'), (21, 'RULE'),
(22, 'CASUAL'), (22, 'BRANDNEW'),
(23, 'FORMAL'), (23, 'STABLE'),
(24, 'CASUAL'), (24, 'AGILE'),
(25, 'CASUAL'), (25, 'AGILE'),
(26, 'CASUAL'), (26, 'DEMOCRACY'),
(27, 'CASUAL'), (27, 'COMFY'),
(28, 'FORMAL'), (28, 'LEADER'),
(29, 'CASUAL'), (29, 'BRANDNEW'),
(30, 'CASUAL'), (30, 'AGILE'),
(31, 'FORMAL'), (31, 'STABLE'),
(32, 'CASUAL'), (32, 'COMFY'),
(33, 'CASUAL'), (33, 'DEMOCRACY'),
(34, 'CASUAL'), (34, 'BRANDNEW'),
(35, 'FORMAL'), (35, 'WATERFALL'),
(36, 'CASUAL'), (36, 'AGILE'),
(37, 'CASUAL'), (37, 'AGILE'),
(38, 'FORMAL'), (38, 'STABLE'),
(39, 'FORMAL'), (39, 'RULE'),
(40, 'CASUAL'), (40, 'DEMOCRACY'),
(41, 'FORMAL'), (41, 'RULE'),
(42, 'CASUAL'), (42, 'AGILE'),
(43, 'CASUAL'), (43, 'COMFY'),
(44, 'FORMAL'), (44, 'LEADER'),
(45, 'CASUAL'), (45, 'DEMOCRACY'),
(46, 'CASUAL'), (46, 'BRANDNEW'),
(47, 'CASUAL'), (47, 'AGILE'),
(48, 'FORMAL'), (48, 'STABLE'),
(49, 'FORMAL'), (49, 'WATERFALL'),
(50, 'CASUAL'), (50, 'COMFY'),
(51, 'CASUAL'), (51, 'BRANDNEW'),
(52, 'FORMAL'), (52, 'DEMOCRACY'),
(53, 'FORMAL'), (53, 'RULE'),
(54, 'CASUAL'), (54, 'COMFY'),
(55, 'CASUAL'), (55, 'BRANDNEW'),
(56, 'FORMAL'), (56, 'STABLE'),
(57, 'FORMAL'), (57, 'WATERFALL'),
(58, 'CASUAL'), (58, 'AGILE'),
(59, 'CASUAL'), (59, 'BRANDNEW'),
(60, 'FORMAL'), (60, 'RULE'),
(61, 'CASUAL'), (61, 'DEMOCRACY'),
(62, 'FORMAL'), (62, 'STABLE'),
(63, 'FORMAL'), (63, 'WATERFALL'),
(64, 'CASUAL'), (64, 'BRANDNEW'),
(65, 'FORMAL'), (65, 'LEADER'),
(66, 'CASUAL'), (66, 'AGILE'),
(67, 'CASUAL'), (67, 'BRANDNEW'),
(68, 'FORMAL'), (68, 'RULE'),
(69, 'CASUAL'), (69, 'AGILE'),
(70, 'CASUAL'), (70, 'DEMOCRACY'),
(71, 'CASUAL'), (71, 'BRANDNEW'),
(72, 'FORMAL'), (72, 'STABLE'),
(73, 'FORMAL'), (73, 'WATERFALL'),
(74, 'CASUAL'), (74, 'COMFY'),
(75, 'CASUAL'), (75, 'BRANDNEW'),
(76, 'FORMAL'), (76, 'RULE'),
(77, 'FORMAL'), (77, 'LEADER'),
(78, 'CASUAL'), (78, 'DEMOCRACY'),
(79, 'FORMAL'), (79, 'RULE'),
(80, 'CASUAL'), (80, 'AGILE'),
(81, 'CASUAL'), (81, 'BRANDNEW'),
(82, 'FORMAL'), (82, 'STABLE'),
(83, 'CASUAL'), (83, 'BRANDNEW'),
(84, 'FORMAL'), (84, 'WATERFALL'),
(85, 'CASUAL'), (85, 'AGILE'),
(86, 'FORMAL'), (86, 'STABLE'),
(87, 'CASUAL'), (87, 'BRANDNEW'),
(88, 'CASUAL'), (88, 'DEMOCRACY'),
(89, 'FORMAL'), (89, 'RULE'),
(90, 'FORMAL'), (90, 'WATERFALL'),
(91, 'CASUAL'), (91, 'BRANDNEW'),
(92, 'CASUAL'), (92, 'AGILE'),
(93, 'FORMAL'), (93, 'RULE'),
(94, 'CASUAL'), (94, 'COMFY'),
(95, 'CASUAL'), (95, 'BRANDNEW'),
(96, 'FORMAL'), (96, 'STABLE'),
(97, 'FORMAL'), (97, 'WATERFALL'),
(98, 'CASUAL'), (98, 'DEMOCRACY'),
(99, 'CASUAL'), (99, 'BRANDNEW');
-- 팀별 프로젝트 목표 설정
INSERT INTO TEAM_TEAM_PREFERENCE (TEAM_TEAM_ID, TEAM_PREFERENCE) VALUES
(1, 'JOB'), (1, 'PORTFOLIO'),
(2, 'AWARD'), (2, 'STUDY'),
(3, 'PORTFOLIO'), (3, 'JOB'),
(4, 'JOB'), (4, 'PROFESSIONAL'),
(5, 'IDEA'), (5, 'PORTFOLIO'),
(6, 'STUDY'), (6, 'PROFESSIONAL'),
(7, 'JOB'), (7, 'QUICK'),
(8, 'STUDY'), (8, 'AWARD'),
(9, 'PORTFOLIO'), (9, 'QUICK'),
(10, 'PROFESSIONAL'), (10, 'IDEA'),
(11, 'PROFESSIONAL'), (11, 'AWARD'),
(12, 'STUDY'), (12, 'PORTFOLIO'),
(13, 'PROFESSIONAL'), (13, 'JOB'),
(14, 'PORTFOLIO'), (14, 'QUALITY'),
(15, 'PROFESSIONAL'), (15, 'JOB');

-- 팀별 프로젝트 분위기 설정
INSERT INTO TEAM_TEAM_VIVE (TEAM_TEAM_ID, TEAM_VIVE) VALUES
(1, 'CASUAL'), (1, 'AGILE'),
(2, 'FORMAL'), (2, 'BRANDNEW'),
(3, 'CASUAL'), (3, 'AGILE'),
(4, 'FORMAL'), (4, 'WATERFALL'),
(5, 'CASUAL'), (5, 'BRANDNEW'),
(6, 'FORMAL'), (6, 'DEMOCRACY'),
(7, 'CASUAL'), (7, 'AGILE'),
(8, 'FORMAL'), (8, 'STABLE'),
(9, 'CASUAL'), (9, 'AGILE'),
(10, 'FORMAL'), (10, 'RULE'),
(11, 'FORMAL'), (11, 'STABLE'),
(12, 'CASUAL'), (12, 'DEMOCRACY'),
(13, 'FORMAL'), (13, 'WATERFALL'),
(14, 'CASUAL'), (14, 'AGILE'),
(15, 'FORMAL'), (15, 'RULE');
